language: node_js
node_js:
  - '4'
  - '5'
  - 'node'

script:
  - "npm test"
  - "npm run test:travis"

after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"